export const supporto = [
  {
    id: "autocannon_ac8",
    nome: "Autocannon (AC-8)",
    categoria: "Arma di supporto",
    tier: "S",
    ap: 4,
    danno: 325,
    dannoExplosivo: 150,
    cadenzaTiro: 250,
    dps: 1979,
    capienza: 10,
    caricatori: 5,
    totaleColpi: 60,
    ricarica: "1.7s",
    descrizione: "Non è la migliore in un singolo ruolo, ma è tra le migliori in quasi tutto. La versatilità è il suo punto forte.",
    pro: ["Versatilità altissima", "Forte su tanti bersagli", "Ottimo all-rounder"],
    contro: ["Richiede gestione della ricarica e buon posizionamento"]
  },
  {
    id: "eat",
    nome: "Expendable Anti-Tank (EAT)",
    categoria: "Arma di supporto",
    tier: "A",
    ap: 6,
    danno: 2000,
    dannoExplosivo: 150,
    capienza: 1,
    totaleColpi: 1,
    descrizione: "Uno dei modi più semplici ed efficaci per abbattere bersagli pesanti. Cooldown corto e nessuno zaino richiesto.",
    pro: ["Anti-heavy immediato", "Cooldown corto", "Nessuno zaino"],
    contro: ["Monouso", "Richiede precisione"]
  },
  {
    id: "quasar_las99",
    nome: "Quasar Cannon (LAS-99)",
    categoria: "Arma di supporto",
    tier: "A",
    ap: 6,
    danno: 2000,
    dannoExplosivo: 150,
    capienza: "Calore",
    ricarica: "15s (raffreddamento)",
    descrizione: "Anti-tank con munizioni infinite ma tempo di carica. Molto forte se hai spazio per sparare.",
    pro: ["Munizioni infinite", "Forte contro pesanti", "Indipendente da zaino"],
    contro: ["Carica lenta", "Vulnerabile durante il puntamento"]
  },
  {
    id: "recoilless_gr8",
    nome: "Recoilless Rifle (GR-8)",
    categoria: "Arma di supporto",
    tier: "A",
    ap: 6,
    danno: 3200,
    dannoExplosivo: 150,
    capienza: 1,
    caricatori: 5,
    totaleColpi: 6,
    ricarica: "4s",
    descrizione: "Molto affidabile e devastante contro quasi tutti i bersagli pesanti.",
    pro: ["Danno enorme", "Affidabile", "Forte contro heavy"],
    contro: ["Ricarica statica", "Richiede zaino"]
  }
];
